Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -50,13 +50,14 @@ jobs:
           name: "Creating cluster"
           command: |
             echo 'Pre-check before creating...'
-            aws eks describe-cluster --name ${EKS_CLUSTER_NAME}
-            if [ $? -ne 0 ]; then
-              echo 'Cluster not found. Creating new cluster...'
-              eksctl create cluster --name ${EKS_CLUSTER_NAME} --nodes 3 --nodes-min 1 --nodes-max 5 --region ${AWS_REGION}
-            else
-              echo 'Cluster existed. Skiping...'
-            fi
+            eksctl create cluster --name ${EKS_CLUSTER_NAME} --nodes 3 --nodes-min 1 --nodes-max 5 --region ${AWS_REGION}
+            # aws eks describe-cluster --name ${EKS_CLUSTER_NAME}
+            # if [ $? -ne 0 ]; then
+              # echo 'Cluster not found. Creating new cluster...'
+              # eksctl create cluster --name ${EKS_CLUSTER_NAME} --nodes 3 --nodes-min 1 --nodes-max 5 --region ${AWS_REGION}
+            # else
+              # echo 'Cluster existed. Skiping...'
+            # fi
 
   k8s-deployment:
     executor: docker-ex
